services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: charityapp_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d charity"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  go:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: dcharityapp_go
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    # env_file:
    #   - .env
    # environment:
    #   - DB_HOST=database
    #   - DB_PORT=5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
