services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: charityapp_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: charity
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d charity"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  go:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: dcharityapp_go
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
